"""cert_sim.py - shared model for the statistical-stopping design (stdlib only; no numpy on this box).

A research program is simulated as a closed-then-open population of MATERIAL holes in a frozen plan
snapshot, searched by T blind panels per round. Rebuilt 2026-09-30 after the 15:26 CDT reboot deleted
the first implementation; every number the design cites is regenerated by the scripts beside this file.

Model (all parameters in Cfg):
- Hole i, panel j (family f_j, context strategy s_j):
      logit p_ij = alpha + shift + d_i + g_{i,f_j} + h_{i,(f_j,s_j)} + e_ijk
  d_i  ~ N(0, sd_d)   hole difficulty, shared by every panel             (heterogeneity, model Mh)
  g    ~ N(0, sd_f)   family x hole effect, PERSISTENT across rounds     (shared blind spots of a family)
  h    ~ N(0, sd_s)   family-strategy x hole effect, persistent
  e    ~ N(0, sd_e)   per-run noise, redrawn every round
  A family can be correlated with another (Fable with Opus): g_F = rho*g_A + sqrt(1-rho^2)*z.
- A fraction u of holes is UNIVERSALLY BLIND (p = 0 for every panel; Link 2003's unidentifiable mass).
- Round k: every live item (real hole or seed) is exposed to all T panels. A real hole caught by >= 1
  panel is verified (assumed perfect here) and FIXED between rounds; each fix spawns Poisson(b) new
  holes (fix-born, fresh difficulty). A caught seed is removed. A round with 0 real holes caught is DRY.
- Carried seeds: s seeds planted at the first freeze (round 1) with the same difficulty law as real
  holes (never universally blind), removed only when caught. Shadow seeds: one per applied fix,
  planted in the edited span, carried thereafter (they age exactly like fix-born holes).
- Optional pre-freeze DISCOVERY phase (P1-P3): holes are removed with logit a + lam*d_i + N(0, sd);
  survivors of discovery are harder than freshly written seeds. Optional seed PRE-SCREEN applies the
  same filter to candidate seeds (survivor-matched seeding).
- Stop: K consecutive dry rounds; optionally the estimated residual must also be <= mu_target, with
  at most R_ext extension rounds, after which the program ends in an operator DECISION (never loops).
"""
import math
import random
from dataclasses import dataclass, field


def logistic(x):
    if x < -35:
        return 0.0
    return 1.0 / (1.0 + math.exp(-x))


# ---------------------------------------------------------------- panel compositions
# DIV8: Opus x2, codex x2, gemini x2, and an Anthropic slot (Opus/Fable) x2 correlated with Opus.
DIV8 = dict(panels=[("A", 0), ("A", 1), ("B", 0), ("B", 1), ("C", 0), ("C", 1), ("D", 0), ("D", 1)],
            corr={"D": ("A", 0.6)})
# SAME8: eight Opus panels, two briefs.
SAME8 = dict(panels=[("A", s % 2) for s in range(8)], corr={})
# DIV16: the same four families, four strategies each.
DIV16 = dict(panels=[(f, s) for f in "ABCD" for s in range(4)], corr={"D": ("A", 0.6)})
# DIV8 with four independent families (upper reference).
DIV8IND = dict(panels=DIV8["panels"], corr={})


@dataclass
class Cfg:
    N0: int = 60
    u: float = 0.05
    comp: dict = field(default_factory=lambda: DIV8)
    alpha: float = -1.2
    sd_d: float = 1.2
    sd_f: float = 1.0
    sd_s: float = 0.5
    sd_e: float = 0.3
    b: float = 0.1
    K: int = 3
    s: int = 60                 # carried seeds
    seed_shift: float = 0.0     # + = seeds easier than real holes
    shadow: bool = True         # one shadow seed per fix
    fresh_end: int = 0          # fresh seeds planted on every new snapshot (the rejected design)
    mu_target: float = None     # None = stop on K dry rounds alone
    R_ext: int = 2
    R_max: int = 40
    disc: dict = None           # {"N_pre":..., "a":..., "lam":..., "sd":...}
    prescreen: bool = False     # apply the discovery filter to candidate seeds
    pred_draws: int = 2000
    cap_live: int = 3000       # a loop whose live-hole count passes this has diverged
    fp: float = 0.0            # false MATERIAL findings per round that survive verification (Poisson)
    orphan: float = 0.0        # per applied fix, chance each live carried seed's anchor is rewritten (censored)


def _families(comp):
    fams = []
    for f, _ in comp["panels"]:
        if f not in fams:
            fams.append(f)
    # bases first
    return sorted(fams, key=lambda f: 1 if f in comp["corr"] else 0)


def new_item(rng, cfg, shift=0.0, blind_ok=True):
    comp = cfg.comp
    blind = blind_ok and (rng.random() < cfg.u)
    d = rng.gauss(0.0, cfg.sd_d)
    g = {}
    for f in _families(comp):
        if f in comp["corr"]:
            base, rho = comp["corr"][f]
            g[f] = rho * g[base] + math.sqrt(1 - rho * rho) * rng.gauss(0.0, cfg.sd_f)
        else:
            g[f] = rng.gauss(0.0, cfg.sd_f)
    h = {}
    z = []
    for f, s in comp["panels"]:
        if (f, s) not in h:
            h[(f, s)] = rng.gauss(0.0, cfg.sd_s)
        z.append(cfg.alpha + shift + d + g[f] + h[(f, s)])
    return {"blind": blind, "d": d, "z": z}


def detect(rng, item, sd_e):
    """number of panels that catch this item in one round (0 for a universally blind item)"""
    if item["blind"]:
        return 0
    c = 0
    for zj in item["z"]:
        if rng.random() < logistic(zj + rng.gauss(0.0, sd_e)):
            c += 1
    return c


def poisson(rng, lam):
    if lam <= 0:
        return 0
    if lam < 40:
        L = math.exp(-lam)
        k, p = 0, 1.0
        while True:
            p *= rng.random()
            if p <= L:
                return k
            k += 1
    return max(0, int(round(rng.gauss(lam, math.sqrt(lam)))))


# ---------------------------------------------------------------- exact binomial bounds
def _binom_cdf(k, n, p):
    if p <= 0:
        return 1.0
    if p >= 1:
        return 1.0 if k >= n else 0.0
    s = 0.0
    lp, lq = math.log(p), math.log1p(-p)
    for i in range(0, k + 1):
        s += math.exp(math.lgamma(n + 1) - math.lgamma(i + 1) - math.lgamma(n - i + 1) + i * lp + (n - i) * lq)
    return min(1.0, s)


def cp_upper(k, n, a=0.05):
    """one-sided Clopper-Pearson upper bound on p given k successes in n"""
    if k >= n:
        return 1.0
    lo, hi = 0.0, 1.0
    for _ in range(60):
        mid = (lo + hi) / 2
        if _binom_cdf(k, n, mid) > a:
            lo = mid
        else:
            hi = mid
    return hi


def cp_lower(k, n, a=0.05):
    if k <= 0:
        return 0.0
    return 1.0 - cp_upper(n - k, n, a)


# ---------------------------------------------------------------- estimators
def ratio_est(F, k_left, s):
    """carried-seed ratio (Mills/Lincoln-Petersen with the seeds as the marked set)"""
    if s <= 0:
        return 0.0, 0.0
    pt = (k_left + 0.5) / (s + 1.0)
    pu = cp_upper(k_left, s)
    mu = F * pt / (1 - pt)
    mu_up = F * pu / (1 - pu) if pu < 1 else float("inf")
    return mu, mu_up


def predictive_draws(rng, F, k_left, s, n, flat=True):
    """posterior-predictive draws of the residual count R.
    pi ~ Beta(k_left+.5, s-k_left+.5) (Jeffreys); R | pi ~ NegBin(r = F+1 (flat prior on N) or F, 1-pi)."""
    out = []
    if s <= 0:
        return [0] * n
    r = F + 1 if flat else F
    for _ in range(n):
        pi = rng.betavariate(k_left + 0.5, s - k_left + 0.5)
        if r <= 0 or pi <= 0:
            out.append(0)
            continue
        lam = rng.gammavariate(r, pi / (1 - pi)) if pi < 1 else 1e9
        out.append(poisson(rng, lam))
    return out


def quantile(xs, q):
    ys = sorted(xs)
    i = min(len(ys) - 1, max(0, int(math.ceil(q * len(ys))) - 1))
    return ys[i]


def chao2_bc(S, Q1, Q2, T):
    return S + ((T - 1) / T) * Q1 * (Q1 - 1) / (2 * (Q2 + 1))


def jk2(S, Q1, Q2, T):
    return S + ((2 * T - 3) / T) * Q1 - ((T - 2) ** 2 / (T * (T - 1))) * Q2


def mann_whitney_z(xs, ys):
    """z for H1: xs tend to be LARGER than ys (normal approx with tie correction)"""
    n1, n2 = len(xs), len(ys)
    if n1 < 3 or n2 < 3:
        return 0.0
    allv = sorted([(v, 0) for v in xs] + [(v, 1) for v in ys])
    ranks = [0.0] * len(allv)
    i = 0
    ties = 0.0
    while i < len(allv):
        j = i
        while j + 1 < len(allv) and allv[j + 1][0] == allv[i][0]:
            j += 1
        r = (i + j) / 2 + 1
        for t in range(i, j + 1):
            ranks[t] = r
        tlen = j - i + 1
        ties += tlen ** 3 - tlen
        i = j + 1
    R1 = sum(r for r, (v, grp) in zip(ranks, allv) if grp == 0)
    U1 = R1 - n1 * (n1 + 1) / 2
    N = n1 + n2
    var = n1 * n2 / 12.0 * ((N + 1) - ties / (N * (N - 1)))
    if var <= 0:
        return 0.0
    return (U1 - n1 * n2 / 2) / math.sqrt(var)


# ---------------------------------------------------------------- one research program
def program(rng, cfg):
    T = len(cfg.comp["panels"])
    # ---- the population entering certification
    if cfg.disc:
        D = cfg.disc
        orig = []
        for _ in range(D["N_pre"]):
            it = new_item(rng, cfg)
            eta = D["a"] + D["lam"] * it["d"] + rng.gauss(0.0, D["sd"])
            if rng.random() >= logistic(eta):      # survived discovery
                orig.append(it)
    else:
        orig = [new_item(rng, cfg) for _ in range(cfg.N0)]
    seeds = []
    tries = 0
    while len(seeds) < cfg.s and tries < 100 * max(1, cfg.s):
        tries += 1
        sd = new_item(rng, cfg, shift=cfg.seed_shift, blind_ok=False)
        if cfg.prescreen and cfg.disc:
            D = cfg.disc
            eta = D["a"] + D["lam"] * sd["d"] + rng.gauss(0.0, D["sd"])
            if rng.random() < logistic(eta):
                continue                            # the pre-screen caught it: discard, as discovery would
        seeds.append(sd)
    N0_total = len(orig)
    N0_det = sum(1 for it in orig if not it["blind"])

    live_orig, live_fix, live_seed, live_shadow = list(orig), [], list(seeds), []
    s_shadow = 0
    fresh = []
    fresh_planted_on_last = 0
    fresh_caught_on_last = 0
    F_orig = F_fix = 0
    n_fix = 0
    dry = 0
    first_gate = None
    k = 0
    found_per_round = []
    r1 = {}
    status = None
    fb_born = 0
    fp_total = 0
    orphaned = 0
    while True:
        k += 1
        # ---- the round
        caught_o, keep_o, cnt_o = [], [], []
        for it in live_orig:
            c = detect(rng, it, cfg.sd_e)
            if c:
                caught_o.append(it)
                cnt_o.append(c)
            else:
                keep_o.append(it)
        caught_f, keep_f = [], []
        for it in live_fix:
            c = detect(rng, it, cfg.sd_e)
            (caught_f if c else keep_f).append(it)
        keep_s, cnt_s = [], []
        for it in live_seed:
            c = detect(rng, it, cfg.sd_e)
            if c:
                cnt_s.append(c)
            else:
                keep_s.append(it)
        keep_sh = [it for it in live_shadow if not detect(rng, it, cfg.sd_e)]
        keep_fr = []
        for it in fresh:
            if detect(rng, it, cfg.sd_e):
                fresh_caught_on_last += 1
            else:
                keep_fr.append(it)
        if k == 1:
            Q = [0] * (T + 1)
            for c in cnt_o:
                Q[c] += 1
            S1 = len(cnt_o)
            R1s = len(cnt_s) / max(1, len(live_seed))
            r1 = dict(S1=S1, Q1=Q[1], Q2=Q[2],
                      chao2=chao2_bc(S1, Q[1], Q[2], T), jk2=jk2(S1, Q[1], Q[2], T),
                      R1_seed=R1s, mills=(S1 / R1s if R1s > 0 else float("inf")),
                      mw_z=mann_whitney_z(cnt_s, cnt_o))
        live_orig, live_fix, live_seed, live_shadow, fresh = keep_o, keep_f, keep_s, keep_sh, keep_fr
        n_fp = poisson(rng, cfg.fp)
        nf = len(caught_o) + len(caught_f) + n_fp
        found_per_round.append(nf)
        F_orig += len(caught_o) + n_fp      # a false positive that passed verification looks like a real find
        F_fix += len(caught_f)
        fp_total += n_fp
        if nf and cfg.orphan > 0:
            p_orph = 1 - (1 - cfg.orphan) ** nf
            kept = []
            for it in live_seed:
                if rng.random() < p_orph:
                    orphaned += 1
                else:
                    kept.append(it)
            live_seed = kept
        if nf > 0:
            dry = 0
            for _ in range(nf):
                births = poisson(rng, cfg.b)
                fb_born += births
                for _ in range(births):
                    live_fix.append(new_item(rng, cfg))
                if cfg.shadow:
                    live_shadow.append(new_item(rng, cfg, shift=cfg.seed_shift, blind_ok=False))
                    s_shadow += 1
            n_fix += nf
            if cfg.fresh_end:
                fresh = [new_item(rng, cfg, shift=cfg.seed_shift, blind_ok=False) for _ in range(cfg.fresh_end)]
                fresh_planted_on_last = cfg.fresh_end
                fresh_caught_on_last = 0
        else:
            dry += 1
        # ---- the gate
        if dry >= cfg.K:
            if first_gate is None:
                first_gate = k
            if cfg.mu_target is None:
                status = "gate"
                break
            mu_o, _ = ratio_est(F_orig, len(live_seed), len(seeds) - orphaned)
            mu_f, _ = ratio_est(F_fix, len(live_shadow), s_shadow)
            if mu_o + mu_f <= cfg.mu_target:
                status = "gate"
                break
            if k - first_gate >= cfg.R_ext:
                status = "decision"
                break
        if k >= cfg.R_max:
            status = "timeout"
            break
        if len(live_orig) + len(live_fix) > cfg.cap_live:
            status = "diverged"
            break

    # ---- the certificate's numbers
    kl, s = len(live_seed), len(seeds) - orphaned
    mu_o, mu_up_o = ratio_est(F_orig, kl, s)
    mu_f, mu_up_f = ratio_est(F_fix, len(live_shadow), s_shadow)
    d_o = predictive_draws(rng, F_orig, kl, s, cfg.pred_draws, flat=True)
    d_f = predictive_draws(rng, F_fix, len(live_shadow), s_shadow, cfg.pred_draws, flat=True) \
        if s_shadow else [0] * cfg.pred_draws
    d_o0 = predictive_draws(rng, F_orig, kl, s, cfg.pred_draws, flat=False)
    tot = [a + b for a, b in zip(d_o, d_f)]
    res_o = sum(1 for it in live_orig if not it["blind"])
    res_f = sum(1 for it in live_fix if not it["blind"])
    blind_left = sum(1 for it in live_orig + live_fix if it["blind"])
    out = dict(
        status=status, rounds=k, panel_runs=k * T, first_gate=first_gate,
        N0_total=N0_total, N0_det=N0_det, F_orig=F_orig, F_fix=F_fix, n_fix=n_fix, fb_born=fb_born,
        seeds=s, seeds_left=kl, shadow=s_shadow, shadow_left=len(live_shadow),
        res_orig=res_o, res_fix=res_f, res_det=res_o + res_f, blind_left=blind_left,
        mu_o=mu_o, mu_up_o=mu_up_o, mu_f=mu_f, mu_up_f=mu_up_f, mu=mu_o + mu_f,
        npred_o=quantile(d_o, 0.95), npred_o_scale=quantile(d_o0, 0.95),
        npred_tot=quantile(tot, 0.95), p_any=sum(1 for x in tot if x >= 1) / len(tot),
        found=found_per_round, fp_total=fp_total, orphaned=orphaned,
        fresh_planted=fresh_planted_on_last, fresh_caught=fresh_caught_on_last,
    )
    out.update(r1)
    return out


def run(cfg, reps, seed=1):
    rng = random.Random(seed)
    return [program(rng, cfg) for _ in range(reps)]


def pct(xs, q):
    return quantile(xs, q) if xs else float("nan")


def mean(xs):
    return sum(xs) / len(xs) if xs else float("nan")
