#!/usr/bin/env bats
# runner-stdin-immunity — the LANDING RUNNERS hand bats a stdin that is /dev/null, always.
#
# THE OTHER HALF OF tests/stub-stdin-drain.bats. That file pins the SUITE side of the 2026-08-05
# defect: three stubs that drained stdin unconditionally and so hung forever whenever the runner's
# stdin was a pipe nobody closes. This file pins the RUNNER side, which is the CHOKEPOINT — bats
# never reads stdin itself, it INHERITS it into every test, so a runner that hands it /dev/null
# immunises all 290 suites at once, including every suite written after today and every stub whose
# drain is perfectly correct for its own subject.
#
# WHY THE RUNNER SIDE MATTERS EVEN THOUGH THE STUBS ARE FIXED. The polarity is inverted against the
# only people who could see it: a developer's hand-run gets a stdin that EOFs, so an unredirected
# call site is GREEN BY HAND and hangs only on the automated path (launchd, the desk, the nightly).
# A hung gate is indistinguishable from a slow one, so nothing alarms. Measured on the unfixed
# suite: stdin=/dev/null → 34/34 in <1s; stdin=an open pipe with a live writer → rc 124.
#
# WHAT IS PINNED:
#   R1  ship-land.sh's gate_bats — THE chokepoint for the smoke runner, the v1 corpus runner and
#       every exoneration re-run — returns PROMPTLY with a draining child and a stdin that never
#       EOFs. Extracted from the real file, never a copy.
#   R2  ANTI-VACUITY for R1: the same extracted function with its `</dev/null` stripped must TIME
#       OUT under the identical fixture. Without R2, a probe that quietly stopped exercising the
#       redirect (a drifted extraction, a fixture whose stdin EOFs after all) reports green forever.
#       The strip is anchored and asserted to match EXACTLY ONCE.
#   R3  postland-verify.sh's BISECT RUNNER — the worst exposure named by the item that produced this
#       change, because it is `git bisect run`'s child and a step that wedges on stdin is a hang
#       nothing decides by content. The runner line is GENERATED by evaluating the real printf out
#       of the real file, so this replays the shipped artifact rather than an approximation of it.
#   R4  ANTI-VACUITY for R3, same contract as R2.
#   R5  CENSUS — every $BATS_BIN execution site in postland-verify.sh carries the redirect, and the
#       population is FLOORED so a rename cannot empty the census into a vacuous pass. This is what
#       fails when a NEW call site is added without one; R1/R3 prove the behaviour, R5 proves the
#       coverage.
#
# 7c32cc6f walled the 12h53m bisect runaway with a wall bound and a step cap. Those CONTAIN this
# failure; the redirect is what removes its cause, so both stay.
#
# Every assertion is `[ ]`, `run`+status, or `… || false`. `[[ ]]` and `(( ))` are errexit-EXEMPT in
# bats and are silently DEAD anywhere but a body's last line — that has burned this repo twice.

setup() {
  REPO="$(cd "$(dirname "$BATS_TEST_FILENAME")/.." && pwd)"
  export HOME="$BATS_TEST_TMPDIR/home"; mkdir -p "$HOME"   # hermeticity ratchet: never the live ~/
  SHIPLAND="$REPO/scripts/ship-land.sh"
  PLV="$REPO/scripts/postland-verify.sh"
  [ -f "$SHIPLAND" ] || skip "ship-land.sh not present in this worktree"
  [ -f "$PLV" ] || skip "postland-verify.sh not present in this worktree"
  # The bound IS the instrument here — with no timeout(1) a hang cannot be told from a pass, so the
  # honest move is to skip rather than to run a probe that can only ever report green.
  TMO="$(command -v timeout || command -v gtimeout || true)"
  [ -n "$TMO" ] || skip "no timeout(1) — a hang would be unmeasurable"
}

# ── the instrument ───────────────────────────────────────────────────────────────────────────────

# A stub `bats` in the HISTORICAL HAZARD SHAPE: it drains stdin unconditionally. It stands in for any
# suite in the corpus that consumes stdin — which is the whole population this change immunises, not
# only the three stubs 5e460544 fixed. Its own correctness is not the subject; the RUNNER's handling
# of it is. (The real stubs are pinned, extracted from their real files, in stub-stdin-drain.bats.)
install_draining_bats() {   # → $STUBDIR/bats
  STUBDIR="$BATS_TEST_TMPDIR/bin"; mkdir -p "$STUBDIR"
  printf '#!/bin/bash\ncat >/dev/null\nexit 0\n' > "$STUBDIR/bats"
  chmod +x "$STUBDIR/bats"
}

# Run a command with an stdin that is OPEN and will never EOF — a FIFO held by a live writer that
# writes nothing. This is the automated-runner condition, reproduced exactly. Prints the exit code;
# 124 is timeout(1)'s "still running when the bound expired", i.e. the hang.
#
# IDIOM AND ITS TWO HARD-WON PROPERTIES ARE stub-stdin-drain.bats':
#   · the writer's stdio is redirected AWAY from the test's — bats reads a test's output pipe to EOF,
#     so a background child inheriting it keeps the TEST alive for the child's whole lifetime;
#   · the second `exec` REPLACES the subshell with sleep, so $! is the process that actually holds
#     fd 9 and `kill` reaches it.
# The sleep outlives the probe's bound so stdin never EOFs while the probe runs — an early EOF would
# let a BROKEN call site exit and read as a pass — and self-reaps if cleanup never runs.
#
# THE BOUND IS AN ARGUMENT AND THE CALLERS PASS OPPOSITE VALUES ON PURPOSE. R1/R3's bound is only
# ever waited out ON FAILURE, so it is generous — a tight one would convict a merely-slow box (this
# corpus runs under a QoS clamp on a machine that is often saturated). R2/R4's is PAID IN FULL on
# every green run, because a hanging mutant never returns, so it is short.
rc_with_never_eof_stdin() {   # $1=bound seconds; $2… = the command
  local bound="$1"; shift
  local fifo w rc
  fifo="$(mktemp -u "$BATS_TEST_TMPDIR/fifo.XXXXXX")"   # trailing Xs only — BSD mktemp ignores others
  mkfifo "$fifo"
  ( exec 9>"$fifo"; exec sleep "$(( bound + 3 ))" ) >/dev/null 2>&1 </dev/null &
  w=$!
  "$TMO" "$bound" "$@" <"$fifo" >/dev/null 2>&1
  rc=$?
  kill "$w" 2>/dev/null || true
  wait "$w" 2>/dev/null || true
  rm -f "$fifo"
  printf '%s' "$rc"
}

# ── R1/R2 — ship-land.sh gate_bats ───────────────────────────────────────────────────────────────

# Extract gate_bats from the REAL file and append a call. Same function-probe idiom as
# tests/ship-land.bats:1463 and tests/gate-home-isolation.bats' probe_fn. SMOKE_DEADLINE is left
# UNSET deliberately: with it set the function wraps its child in its own timeout, and the probe
# would then be measuring THAT bound rather than the redirect.
build_gate_probe() {   # $1=variant(fixed|mutant) → $BATS_TEST_TMPDIR/probe.sh
  local body
  body="$(sed -n '/^gate_bats() {/,/^}/p' "$SHIPLAND")"
  [ -n "$body" ]                                        # an empty extraction is a vacuous pass
  # …and a non-empty extraction can still be the wrong block. This is the line the scrub is built
  # around; ship-land.bats anchors on the same one.
  printf '%s\n' "$body" | grep -qF 'env -u SHIP_LAND_GATE_ROUNDS' || false
  # The redirect must appear EXACTLY ONCE in the body. Zero ⇒ the fix is gone (R1 would then pass
  # only if the fixture were broken, which R2 is what catches); more than one ⇒ the mutation below
  # is ambiguous and the mutant is not the pre-fix function.
  [ "$(printf '%s\n' "$body" | grep -cF '</dev/null')" = "1" ]
  if [ "$1" = mutant ]; then
    body="$(printf '%s\n' "$body" | sed 's|[ ]*</dev/null$||')"
    if printf '%s\n' "$body" | grep -qF '</dev/null'; then return 1; fi
    printf '%s\n' "$body" | grep -qF 'bats "$@"' || false   # the call itself survived the strip
  fi
  { printf '%s\n' "$body"; printf 'gate_bats tests/foo.bats\n'; } > "$BATS_TEST_TMPDIR/probe.sh"
}

@test "R1: gate_bats returns PROMPTLY with a draining child and a stdin that never EOFs" {
  # The regression proper, at ship-land's single chokepoint: every bats the lander runs — the smoke,
  # the v1 corpus, every exoneration re-run — reaches the child through this one call.
  install_draining_bats
  build_gate_probe fixed
  [ "$(rc_with_never_eof_stdin 20 env PATH="$STUBDIR:$PATH" bash "$BATS_TEST_TMPDIR/probe.sh")" = "0" ]
}

@test "R2: ANTI-VACUITY — gate_bats WITHOUT the redirect hangs under the same fixture" {
  # Proves three things at once, none of which R1 can prove alone: the fixture really does present a
  # stdin that never EOFs, the stub really does read it, and the redirect is what makes R1 green.
  install_draining_bats
  build_gate_probe mutant
  [ "$(rc_with_never_eof_stdin 5 env PATH="$STUBDIR:$PATH" bash "$BATS_TEST_TMPDIR/probe.sh")" = "124" ]
}

# ── R3/R4 — postland-verify.sh's bisect runner ───────────────────────────────────────────────────

# Generate the runner's bats line by EVALUATING the real printf out of the real file — the artifact
# under test is text this script writes at run time, so a hand-written approximation of it could pass
# while the shipped generator is broken. $qos is empty on purpose: the QoS prefix execs taskpolicy
# and is orthogonal to stdin, so reducing it keeps the probe hermetic without weakening it.
build_bisect_runner() {   # $1=variant(fixed|mutant) → $BATS_TEST_TMPDIR/runner
  local gen line
  gen="$(grep -F 'printf ' "$PLV" | grep -F '"$qos" "$BATS_BIN" "$file"')"
  [ "$(printf '%s\n' "$gen" | grep -c .)" = "1" ]       # the generator must be found exactly once
  # These three ARE the generator's inputs — postland-verify.sh's printf reads $qos, $BATS_BIN and
  # $file by those exact names — but they are consumed by `eval`, which shellcheck cannot see into.
  # shellcheck disable=SC2034
  line="$( qos="" BATS_BIN="$STUBDIR/bats" file="tests/foo.bats"; eval "$gen" )"
  [ "$(printf '%s\n' "$line" | grep -cF '</dev/null')" = "1" ]
  if [ "$1" = mutant ]; then
    line="$(printf '%s\n' "$line" | sed 's|[ ]*</dev/null||')"
    if printf '%s\n' "$line" | grep -qF '</dev/null'; then return 1; fi
  fi
  { printf '#!/bin/bash\n'; printf '%s\n' "$line"; } > "$BATS_TEST_TMPDIR/runner"
  chmod +x "$BATS_TEST_TMPDIR/runner"
}

@test "R3: the bisect runner returns PROMPTLY with a draining child and a stdin that never EOFs" {
  # THE WORST EXPOSURE. This runner is `git bisect run`'s child, so it inherits the daemon's stdin,
  # and it already redirected stdout+stderr — which is exactly why the missing one was invisible.
  install_draining_bats
  build_bisect_runner fixed
  [ "$(rc_with_never_eof_stdin 20 "$BATS_TEST_TMPDIR/runner")" = "0" ]
}

@test "R4: ANTI-VACUITY — the bisect runner WITHOUT the redirect hangs under the same fixture" {
  install_draining_bats
  build_bisect_runner mutant
  [ "$(rc_with_never_eof_stdin 5 "$BATS_TEST_TMPDIR/runner")" = "124" ]
}

# ── R5 — the census ──────────────────────────────────────────────────────────────────────────────

@test "R5: EVERY bats call site in both runners redirects stdin — and the census is not empty" {
  # R1/R3 prove the BEHAVIOUR at two sites; this proves COVERAGE at all of them, and it is the arm
  # that goes red when someone adds a NEW call site without a redirect. Comment lines are excluded:
  # this file's own rationale names $BATS_BIN and would otherwise convict the explanation.
  local sites missing
  sites="$(grep -n '\$BATS_BIN' "$PLV" | grep -v '^[0-9]*: *#' | grep -v '^[0-9]*:BATS_BIN=')"
  # FLOORED, not merely non-empty. A rename of $BATS_BIN would empty this grep and make every
  # assertion below pass vacuously — the exact failure this file exists to prevent elsewhere. 8 is
  # the population measured when the redirects landed; dropping below it means RE-VERIFY the sites,
  # never lower the number.
  [ "$(printf '%s\n' "$sites" | grep -c .)" -ge 8 ]
  missing="$(printf '%s\n' "$sites" | grep -vF '</dev/null' || true)"
  [ -z "$missing" ] || { echo "unredirected \$BATS_BIN call site(s):"; echo "$missing"; false; }
  # ship-land's single site, by its own anchor — one chokepoint, so one line.
  [ "$(grep -c 'bats "\$@" </dev/null' "$SHIPLAND")" = "1" ]
}
