#!/bin/bash
# Shared functions for task list hooks.
# Source: . "$(dirname "$0")/lib/task-helpers.sh"

TASKS_DIR="$HOME/.claude/tasks"

# Find the active task list (most recently modified dir with task .json files).
# Prints the task list ID (directory basename), or empty string if none found.
find_active_list() {
    local best="" best_time=0
    for dir in "$TASKS_DIR"/*/; do
        [ ! -d "$dir" ] && continue
        # Any numeric .json files? (task files are 1.json, 2.json, etc.)
        local latest
        latest=$(ls -t "$dir"/[0-9]*.json 2>/dev/null | head -1)
        [ -z "$latest" ] && continue
        local mtime
        mtime=$(stat -f %m "$latest" 2>/dev/null || echo "0")
        if [ "$mtime" -gt "$best_time" ]; then
            best_time=$mtime
            best=$(basename "$dir")
        fi
    done
    echo "$best"
}

# Regenerate _summary.json for a task list directory.
regenerate_summary() {
    local dir="$1"
    [ ! -d "$dir" ] && return 1
    local listid
    listid=$(basename "$dir")
    local hwm
    hwm=$(cat "$dir/.highwatermark" 2>/dev/null || echo "0")
    case "$hwm" in ''|*[!0-9]*) hwm=0 ;; esac
    local json_files
    json_files=$(find "$dir" -maxdepth 1 -name '*.json' ! -name '_summary.json' 2>/dev/null)
    if [ -z "$json_files" ]; then
        jq -n --arg listid "$listid" --argjson hwm "$hwm" \
          '{taskListId: $listid, highwatermark: $hwm, totalOnDisk: 0,
            pending: 0, in_progress: 0, completed: 0, plans: [], tasks: []}' \
          > "$dir/_summary.json" 2>/dev/null || true
        return 0
    fi
    local temp
    temp=$(mktemp)
    if find "$dir" -maxdepth 1 -name '*.json' ! -name '_summary.json' -exec cat {} + 2>/dev/null \
      | jq -s --arg listid "$listid" --argjson hwm "$hwm" \
        '{taskListId: $listid, highwatermark: $hwm, totalOnDisk: length,
          pending: [.[] | select(.status == "pending")] | length,
          in_progress: [.[] | select(.status == "in_progress")] | length,
          completed: [.[] | select(.status == "completed")] | length,
          plans: ([.[].description | [scan("\\[Plan: ([^]]+)\\]") | .[0]] | .[]] | unique),
          tasks: (sort_by(.id | tonumber))}' \
        > "$temp" 2>/dev/null && [ -s "$temp" ]; then
        mv "$temp" "$dir/_summary.json"
    else
        rm -f "$temp"
    fi
}

# Generate TASKS.md from a _summary.json file.
# Args: $1 = summary json path, $2 = output TASKS.md path, $3 = project dir (for absolute path)
generate_tasks_md() {
    local summary="$1"
    local output="$2"
    local project_dir="${3:-.}"
    [ ! -f "$summary" ] && return 1
    local total
    total=$(jq -r '.totalOnDisk' "$summary" 2>/dev/null)
    if [ "$total" = "0" ] || [ -z "$total" ]; then
        rm -f "$output" 2>/dev/null
        return 0
    fi
    local pending in_progress completed list_id now abs_path
    pending=$(jq -r '.pending' "$summary")
    in_progress=$(jq -r '.in_progress' "$summary")
    completed=$(jq -r '.completed' "$summary")
    list_id=$(jq -r '.taskListId' "$summary")
    now=$(date -u +"%Y-%m-%d %H:%M UTC")
    abs_path=$(cd "$project_dir" 2>/dev/null && pwd)/.claude-tasks/TASKS.md

    {
        echo "<!-- Auto-generated by Claude Code hooks — DO NOT EDIT -->"
        echo "<!-- Regenerated: session start · task create/update · task complete -->"
        echo "<!-- To resume in a new session: Read .claude-tasks/TASKS.md -->"
        echo "<!-- Absolute path: ${abs_path} -->"
        echo ""
        echo "# Active Tasks"
        echo ""
        echo "**${pending} pending** · ${in_progress} in-progress · ${completed} done | ${now}"
        echo ""

        if [ "$pending" -gt 0 ]; then
            echo "## Pending"
            echo ""
            jq -r '.tasks[] | select(.status == "pending") |
                "- [ ] **\(.id). \(.subject)**\n  \(.description | gsub("\n"; "\n  "))\n"' "$summary"
        fi

        if [ "$in_progress" -gt 0 ]; then
            echo "## In Progress"
            echo ""
            jq -r '.tasks[] | select(.status == "in_progress") |
                "- [~] **\(.id). \(.subject)**\n  \(.description | gsub("\n"; "\n  "))\n"' "$summary"
        fi

        if [ "$completed" -gt 0 ]; then
            echo "## Completed"
            echo ""
            jq -r '.tasks[] | select(.status == "completed") |
                "- [x] **\(.id). \(.subject)**"' "$summary"
            echo ""
        fi

        echo "---"
        echo "*Source: \`~/.claude/tasks/${list_id}/\` · JSON: \`.claude-tasks/_current/_summary.json\`*"
    } > "$output"
}
