#!/bin/bash
# GENERATED by scripts/gen-account-map.sh from /Users/chrisren/Development/.worktrees/wt-lc-hf/accounts.json — do not hand-edit.
# Regenerate: scripts/gen-account-map.sh
# shellcheck disable=SC2034  # consumed by whichever script sources this file

# account name, launcher, or fable_launcher -> CC_ACCT_DIR (+ CC_ACCT_IS_FABLE=1 on the
# fable variant, same config dir). Sets globals rather than echoing: callers that need the
# fable flag cannot invoke this via $(...) command substitution — that runs in a subshell,
# so a side-channel var set there never reaches the caller. Call directly:
#   cc_acct_dir_for_name "$x" || { ...unknown...; }; cfg="$CC_ACCT_DIR"
cc_acct_dir_for_name() {
  CC_ACCT_IS_FABLE=0
  CC_ACCT_DIR=""
  case "$1" in
    next|claude) CC_ACCT_DIR="$HOME/.claude-next" ;;
    fable) CC_ACCT_IS_FABLE=1; CC_ACCT_DIR="$HOME/.claude-next" ;;
    next4|claude4) CC_ACCT_DIR="$HOME/.claude-quaternary" ;;
    fable4) CC_ACCT_IS_FABLE=1; CC_ACCT_DIR="$HOME/.claude-quaternary" ;;
    next3|claude3) CC_ACCT_DIR="$HOME/.claude-tertiary" ;;
    fable3) CC_ACCT_IS_FABLE=1; CC_ACCT_DIR="$HOME/.claude-tertiary" ;;
    next2|claude2) CC_ACCT_DIR="$HOME/.claude-secondary" ;;
    fable2) CC_ACCT_IS_FABLE=1; CC_ACCT_DIR="$HOME/.claude-secondary" ;;
    *) return 1 ;;
  esac
}

# config-dir basename (or a declared alias, e.g. the primary account's mirror dir) -> name.
cc_acct_name_for_dir_basename() {
  case "$1" in
    .claude-next|claude-next|claude) echo "next" ;;
    .claude-quaternary|claude-quaternary) echo "next4" ;;
    .claude-tertiary|claude-tertiary) echo "next3" ;;
    .claude-secondary|claude-secondary) echo "next2" ;;
    *) echo "" ;;
  esac
}

CC_ACCT_NAMES="next next4 next3 next2"
