#!/bin/bash
# Regenerate lib/account-map.generated.sh from accounts.json's accounts[] array — the single
# source of truth for account-name <-> config-dir mapping. Run after editing accounts.json;
# install.sh calls this automatically so it never drifts.
#
# Why generated rather than read live at call time: several consumers (cc-context, cc-value,
# cc-board) run on hot paths (every statusline render) where forking jq per lookup is measurable
# overhead, and macOS ships bash 3.2 (no associative arrays), so the portable form is a `case`
# statement. Codegen keeps that fast path while making accounts.json the only place account
# count/names/dirs are declared — works for any N >= 1 accounts, not just the hardcoded 4 this
# replaced.
#
# Usage: scripts/gen-account-map.sh [path/to/accounts.json]
# shellcheck disable=SC2016  # single quotes below are intentional: they emit literal `case "$1"`
# text into the generated file, not an interpolation this script means to perform.
set -euo pipefail

# Resolve $0 through its symlinks before deriving REPO_DIR: ~/.claude/scripts/ is per-file
# SYMLINKS into the checkout (install.sh), so an unresolved `dirname "$0"/..` on that deployed
# path is ~/.claude, not the repo — self-path-lint.sh's canonical loop (BSD-safe, no readlink -f).
SELF="$0"
while [ -L "$SELF" ]; do
  _d="$(cd "$(dirname "$SELF")" && pwd)"
  SELF="$(readlink "$SELF")"
  case "$SELF" in /*) ;; *) SELF="$_d/$SELF" ;; esac
done
REPO_DIR="$(cd "$(dirname "$SELF")/.." && pwd)"
ACCOUNTS_JSON="${1:-$REPO_DIR/accounts.json}"
OUT="$REPO_DIR/lib/account-map.generated.sh"

[ -f "$ACCOUNTS_JSON" ] || { echo "gen-account-map: $ACCOUNTS_JSON not found — copy accounts.json.example to accounts.json first" >&2; exit 1; }
command -v jq >/dev/null 2>&1 || { echo "gen-account-map: jq required" >&2; exit 1; }

N="$(jq '.accounts | length' "$ACCOUNTS_JSON")"
[ "$N" -ge 1 ] 2>/dev/null || { echo "gen-account-map: $ACCOUNTS_JSON has no accounts[]" >&2; exit 1; }

{
  echo '#!/bin/bash'
  echo "# GENERATED by scripts/gen-account-map.sh from ${ACCOUNTS_JSON} — do not hand-edit."
  echo '# Regenerate: scripts/gen-account-map.sh'
  echo '# shellcheck disable=SC2034  # consumed by whichever script sources this file'
  echo
  echo '# account name, launcher, or fable_launcher -> CC_ACCT_DIR (+ CC_ACCT_IS_FABLE=1 on the'
  echo '# fable variant, same config dir). Sets globals rather than echoing: callers that need the'
  echo '# fable flag cannot invoke this via $(...) command substitution — that runs in a subshell,'
  echo '# so a side-channel var set there never reaches the caller. Call directly:'
  echo '#   cc_acct_dir_for_name "$x" || { ...unknown...; }; cfg="$CC_ACCT_DIR"'
  echo 'cc_acct_dir_for_name() {'
  echo '  CC_ACCT_IS_FABLE=0'
  echo '  CC_ACCT_DIR=""'
  echo '  case "$1" in'
  jq -c '.accounts[]' "$ACCOUNTS_JSON" | while IFS= read -r row; do
    name="$(jq -r '.name' <<<"$row")"
    launcher="$(jq -r '.launcher' <<<"$row")"
    fable_launcher="$(jq -r '.fable_launcher // empty' <<<"$row")"
    fable_name="$(jq -r '.fable_name // empty' <<<"$row")"
    dir="$(jq -r '.config_dir' <<<"$row")"
    dir="${dir/#\~\//\$HOME/}"
    printf '    %s|%s) CC_ACCT_DIR="%s" ;;\n' "$name" "$launcher" "$dir"
    if [ -n "$fable_launcher" ] || [ -n "$fable_name" ]; then
      fable_pat="$fable_launcher"
      [ -n "$fable_name" ] && fable_pat="${fable_pat:+$fable_pat|}$fable_name"
      printf '    %s) CC_ACCT_IS_FABLE=1; CC_ACCT_DIR="%s" ;;\n' "$fable_pat" "$dir"
    fi
  done
  echo '    *) return 1 ;;'
  echo '  esac'
  echo '}'
  echo
  echo '# config-dir basename (or a declared alias, e.g. the primary account'"'"'s mirror dir) -> name.'
  echo 'cc_acct_name_for_dir_basename() {'
  echo '  case "$1" in'
  jq -c '.accounts[]' "$ACCOUNTS_JSON" | while IFS= read -r row; do
    name="$(jq -r '.name' <<<"$row")"
    dir="$(jq -r '.config_dir' <<<"$row")"
    base="${dir##*/}"       # e.g. ".claude-secondary" (basename keeps the leading dot)
    base_nodot="${base#.}"  # e.g. "claude-secondary" — some callers strip it upstream
    aliases="$(jq -r '([.aliases // []][0]) | join("|")' <<<"$row")"
    pattern="$base"
    [ "$base_nodot" != "$base" ] && pattern="$pattern|$base_nodot"
    [ -n "$aliases" ] && pattern="$pattern|$aliases"
    printf '    %s) echo "%s" ;;\n' "$pattern" "$name"
  done
  echo '    *) echo "" ;;'
  echo '  esac'
  echo '}'
  echo
  printf 'CC_ACCT_NAMES="%s"\n' "$(jq -r '[.accounts[].name] | join(" ")' "$ACCOUNTS_JSON")"
} > "$OUT"
chmod +x "$OUT"
echo "gen-account-map: wrote lib/account-map.generated.sh ($N accounts)" >&2
