#!/bin/bash
# mirror-kpmg-deck.sh — refresh skills/kpmg-deck/ from the live working repo.
#
# WHY THIS EXISTS. kpmg-deck is the only skill that is not deployed from this checkout. Every
# other one lives here and reaches ~/.claude/skills/<name>/ as per-file symlinks; kpmg-deck is a
# real directory under ~/.claude with its OWN git history and no remote. Until the mirror existed
# the package had exactly one copy, on one disk.
#
# The first mirror was taken by hand and went stale inside ten minutes — the next commit to the
# working repo touched SKILL.md and the copy here did not move. That is the whole argument for a
# script: a mirror nobody can refresh in one command is a mirror that silently stops being one.
#
# THIS IS NOT THE PROPER FIX and does not pretend to be. Normalising kpmg-deck means putting the
# source here, symlinking the live files back, and wiring it through install.sh like everything
# else. That was left alone deliberately: the live directory is a working git repo, and replacing
# its files with symlinks strips the local history that is the only copy of the commit graph.
# See skills/kpmg-deck/MIRROR.md.
#
# Usage:  bash scripts/mirror-kpmg-deck.sh [--check]
#   --check  report drift and exit 1 if the mirror is stale; write nothing.

set -euo pipefail

SRC="${KPMG_DECK_SRC:-$HOME/.claude/skills/kpmg-deck}"

# RESOLVE $0 THROUGH ITS SYMLINKS BEFORE DERIVING THE ROOT. ~/.claude/{scripts,hooks,bin}/ are
# per-file symlinks into this checkout, so through the live layer `dirname "$0"/..` is ~/.claude —
# which has no skills/ of the repo's shape. The script would not FAIL; it would mirror into the
# wrong tree, and only when invoked through the deployed layer, so a worktree run looks fine.
# No `readlink -f`: GNU-only, and this box is BSD. Canonical loop: _resolve_self() in ship-land.sh.
_self="${BASH_SOURCE[0]}"
while [ -L "$_self" ]; do
  _d="$(cd "$(dirname "$_self")" && pwd)"
  _self="$(readlink "$_self")"
  case "$_self" in /*) ;; *) _self="$_d/$_self" ;; esac
done
DST="$(cd "$(dirname "$_self")/.." && pwd)/skills/kpmg-deck"
CHECK=0
[ "${1:-}" = "--check" ] && CHECK=1

[ -d "$SRC/.git" ] || { echo "mirror-kpmg-deck: no working repo at $SRC" >&2; exit 2; }

cd "$SRC"
DRIFT=0
FAILED=0

# Tracked TEXT files only. Two exclusions, both learned the hard way:
#   *.pptx      build output -- regenerable and binary.
#   symlinks    the deploy step symlinks THIS directory's own HISTORY.md and MIRROR.md back into
#               the live layer, so they can appear in the working repo's `git ls-files`. Copying
#               one would mean copying a file onto itself; cp refuses, and under `set -e` that
#               aborted the whole sync at the first file while reporting success. A sync tool
#               that dies silently on file one is worse than no sync tool.
while IFS= read -r f; do
  case "$f" in *.pptx) continue ;; esac
  [ -L "$SRC/$f" ] && continue
  [ "$SRC/$f" -ef "$DST/$f" ] && continue
  if [ "$CHECK" = 1 ]; then
    if ! cmp -s "$SRC/$f" "$DST/$f" 2>/dev/null; then
      echo "DRIFT  $f"
      DRIFT=1
    fi
  else
    mkdir -p "$DST/$(dirname "$f")"
    if ! cp "$SRC/$f" "$DST/$f"; then
      echo "mirror-kpmg-deck: FAILED to copy $f" >&2
      FAILED=1
    fi
  fi
done < <(git ls-files)

# A file deleted from the working repo must not survive here as a ghost.
while IFS= read -r m; do
  rel="${m#"$DST"/}"
  case "$rel" in MIRROR.md|HISTORY.md) continue ;; esac
  if ! git ls-files --error-unmatch "$rel" >/dev/null 2>&1; then
    if [ "$CHECK" = 1 ]; then echo "STALE  $rel (gone from the working repo)"; DRIFT=1
    else rm -f "$m"; fi
  fi
done < <(find "$DST" -type f)

if [ "$CHECK" = 1 ]; then
  [ "$DRIFT" = 0 ] && echo "mirror-kpmg-deck: in sync"
  exit "$DRIFT"
fi

# The commit messages carry most of this package's reasoning, and the graph itself stays local.
{
  echo "# kpmg-deck — commit history of the working repo"
  echo
  echo "Generated by \`scripts/mirror-kpmg-deck.sh\`. The working repo is \`~/.claude/skills/kpmg-deck\`,"
  echo "which has no remote; this file carries its history's reasoning so the mirror is not just a"
  echo "state with no account of how it got there."
  echo
  echo '```'
  git log --format='%h  %ad  %s%n%w(96,4,4)%b%n' --date=short
  echo '```'
} > "$DST/HISTORY.md"

[ "$FAILED" = 0 ] || { echo "mirror-kpmg-deck: one or more files did not copy -- mirror is INCOMPLETE" >&2; exit 1; }
echo "mirror-kpmg-deck: refreshed $(git ls-files | grep -vc '\.pptx$') files -> skills/kpmg-deck/"
