#!/bin/bash
# mirror-kpmg-deck.sh — refresh skills/kpmg-deck/ from the live working repo.
#
# WHY THIS EXISTS. kpmg-deck is the only skill that is not deployed from this checkout. Every
# other one lives here and reaches ~/.claude/skills/<name>/ as per-file symlinks; kpmg-deck is a
# real directory under ~/.claude with its OWN git history and no remote. Until the mirror existed
# the package had exactly one copy, on one disk.
#
# The first mirror was taken by hand and went stale inside ten minutes — the next commit to the
# working repo touched SKILL.md and the copy here did not move. That is the whole argument for a
# script: a mirror nobody can refresh in one command is a mirror that silently stops being one.
#
# THIS IS NOT THE PROPER FIX and does not pretend to be. Normalising kpmg-deck means putting the
# source here, symlinking the live files back, and wiring it through install.sh like everything
# else. That was left alone deliberately: the live directory is a working git repo, and replacing
# its files with symlinks strips the local history that is the only copy of the commit graph.
# See skills/kpmg-deck/MIRROR.md.
#
# Usage:  bash scripts/mirror-kpmg-deck.sh [--check]
#   --check  report drift and exit 1 if the mirror is stale; write nothing.

set -euo pipefail

SRC="${KPMG_DECK_SRC:-$HOME/.claude/skills/kpmg-deck}"
DST="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/skills/kpmg-deck"
CHECK=0
[ "${1:-}" = "--check" ] && CHECK=1

[ -d "$SRC/.git" ] || { echo "mirror-kpmg-deck: no working repo at $SRC" >&2; exit 2; }

cd "$SRC"
DRIFT=0

# Tracked TEXT files only. Build output (*.pptx) is excluded: it is regenerable and binary.
while IFS= read -r f; do
  case "$f" in *.pptx) continue ;; esac
  if [ "$CHECK" = 1 ]; then
    if ! cmp -s "$SRC/$f" "$DST/$f" 2>/dev/null; then
      echo "DRIFT  $f"
      DRIFT=1
    fi
  else
    mkdir -p "$DST/$(dirname "$f")"
    cp "$SRC/$f" "$DST/$f"
  fi
done < <(git ls-files)

# A file deleted from the working repo must not survive here as a ghost.
while IFS= read -r m; do
  rel="${m#"$DST"/}"
  case "$rel" in MIRROR.md|HISTORY.md) continue ;; esac
  if ! git ls-files --error-unmatch "$rel" >/dev/null 2>&1; then
    if [ "$CHECK" = 1 ]; then echo "STALE  $rel (gone from the working repo)"; DRIFT=1
    else rm -f "$m"; fi
  fi
done < <(find "$DST" -type f)

if [ "$CHECK" = 1 ]; then
  [ "$DRIFT" = 0 ] && echo "mirror-kpmg-deck: in sync"
  exit "$DRIFT"
fi

# The commit messages carry most of this package's reasoning, and the graph itself stays local.
{
  echo "# kpmg-deck — commit history of the working repo"
  echo
  echo "Generated by \`scripts/mirror-kpmg-deck.sh\`. The working repo is \`~/.claude/skills/kpmg-deck\`,"
  echo "which has no remote; this file carries its history's reasoning so the mirror is not just a"
  echo "state with no account of how it got there."
  echo
  echo '```'
  git log --format='%h  %ad  %s%n%w(96,4,4)%b%n' --date=short
  echo '```'
} > "$DST/HISTORY.md"

echo "mirror-kpmg-deck: refreshed $(git ls-files | grep -vc '\.pptx$') files -> skills/kpmg-deck/"
