font_family Monaco
font_size 18.0
modify_font cell_height 94%
window_padding_width 0 5 0 5
window_title_bar_min_windows 1
window_title_bar_align left
window_title_bar_active_background #2f62d8
window_title_bar_active_foreground #ffffff
window_title_bar_inactive_background #3f5590
window_title_bar_inactive_foreground #f4f6fd
window_border_width 1pt
draw_minimal_borders no
placement_strategy top
window_drag_tolerance 6
allow_remote_control yes
enabled_layouts splits,tall,fat,grid,stack
confirm_os_window_close 0
update_check_interval 0
